### ISSUE TITLE
 The event indicates "The parent prefix was not able to be computed" when the real problem is that the user set an invalid tenant

### ISSUE THREAD

**Issue by henrybear327** [netbox-community/netbox-operator#132]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via netbox operator maintainers.
- [X] Existing open issues have been checked and this is not a duplicate.

### What happened?

If you use a PrefixClaim using parentPrefixSelector with an invalid Tenant (a Tenant that doesn't exist in NetBox), the Event will show
```
The parent prefix was not able to be computed. no parent prefix can be obtained with the query conditions set in ParentPrefixSelector, err = <nil>, number of candidates = 0
```

See https://github.com/netbox-community/netbox-operator/pull/90#issuecomment-2475888085

### What did you expect to happen?

An error message such as `invalid Tenant supplied` should be returned. 

### How can we reproduce it (as minimally and precisely as possible)?

Use the following CR
```
apiVersion: netbox.dev/v1
kind: PrefixClaim
metadata:
  name: prefixclaim-customfields-sample
spec:
  tenant: "MY_TENANT that doesn't exist"
  site: "DM-Akron"
  preserveInNetbox: true
  prefixLength: "/31"
  parentPrefixSelector: # The keys and values are case-sensitive
    environment: "PostProduction"
    poolName: "Pool 1"
```

### Netbox operator version

Latest on main (the issue was discovered on https://github.com/netbox-community/netbox-operator/pull/90 before merging)
