### ISSUE TITLE
Implement dynamic selection of parent prefix from a set of custom fields

### ISSUE THREAD

**Issue by henrybear327** [netbox-community/netbox-operator#79]
### What would you like to be added?

Currently, the parent prefix can only be defined from the `ParentPrefix` field in the CRD. 

We would like to extend it such that we can also use the `parentPrefixSelector` to obtain the parent prefix and perform prefix claims. 

The added selector may look something like this 
```
parentPrefixSelector:
    customFieldX: asdf
    customFieldY: wxyz
    customFieldZ: true
```

### Why is this needed?

Adding more flexibility for specifying the parent prefix, as we can pass it in by name (e.g. custom fields) instead of hard-coded values.
